#!/bin/sh
# Outputs the seconds since the thing identified by the first argument
# was last modified (not created).

ageof() {
  ageofpath="$1"
  #if [[ -z "$ageofpath" ]]; then
  if [ -z "$ageofpath" ]; then
    echo 'usage: ageof <path>'
    return 1
  fi
  echo $(( $(date +%s) - $(date -r "$ageofpath" +%s) ))
}

ageof "$@"
