#!/bin/sh 

########################################################################
# 
# 	Scriptname	cpdocuments
# 
# 	Description:	copy to documents folder
# 
########################################################################

DOCUMENTS=~/Documents

cp $@ $DOCUMENTS

