#!/bin/sh 

########################################################################
# 
# 	Scriptname	lsdocuments
# 
# 	Description:	list documents folder
# 
########################################################################

DOCUMENTS=~/Documents

ls $DOCUMENTS

