#!/bin/sh -x

xsetroot -name "resetting...."
sleep 1

printip() {
	wlan="`ifconfig wlan0  2>/dev/null | grep inet | head -n 1 | cut -d ' ' -f 2`"
	ue="`ifconfig ue0 2> /dev/null  | grep inet | head -n 1 | cut -d ' ' -f 2`"
	echo -n $wlan $ue 
}

printwho() {
	echo -n "`whoami`@`hostname`"
}

printcpu(){
	echo -n "c:`top -d 1 | grep -m 1 CPU | cut -d ',' -f 1 | cut -w  -f 2`"
}

printmem(){
	echo -n "m:`top -d 1 | grep Mem | cut -d ',' -f 5 |sed s/\ Free// | tr -d ' '`"
}

printload() {
	echo -n "l:`uptime | cut -d ':' -f 3  | sed -e 's/,.*//' -e 's/^ //'`"
}

printdate() {
	echo -n "`date | cut -d ' ' -f 1-4 | cut -d ':' -f 1-2`"
}

printbatt() {
	echo -n "b:`/usr/sbin/acpiconf -i 0 | grep 'Remaining capacity' | cut -w -f 3 `"
}




while true 
do
	xsetroot -name "`printdate`  `printbatt`,`printload`,`printmem`,`printcpu`  `printip`  `printwho`"
	sleep 1
done

