#!/usr/local/bin/bash

DMENU='dmenu -i -l 20 -p'

selected="$(ps -U "$USER" | dmenu -i -l 20 -p "Search for process to kill:" "$@" | cut -f 2 -w)"

if [[ -n $selected ]]; then
	answer="$(echo -e "No\nYes" | dmenu -i -l 20 -p "Kill $selected?" "$@")"

	if [[ $answer == "Yes" ]]; then
		kill -9 "${selected%% *}"
		echo "Process $selected has been killed." && exit 0
	else
		echo "Program terminated." && exit 1
	fi
fi

