#!/bin/sh

########################################################################
# 
# 	Scriptname	lsprojects
# 
# 	Description:	what projects have I on this machine
# 
########################################################################

ls ~/Projects

