#!/bin/sh 

########################################################################
# 
# 	Scriptname	mvdocuments
# 
# 	Description:	move to documents folder
# 
########################################################################

DOCUMENTS=~/Documents

mv $@ $DOCUMENTS

