#!/bin/sh
########################################################################
# 
# 	Scriptname	mvexample
# 
# 	Description:	mv example file to examples directory
# 
########################################################################

EXAMPLE=$@
EXAMPLEDIR=$HOME/bin/examples

test -d $EXAMPLE && chmod 755 $EXAMPLE || chmod 644 $EXAMPLE
mv $EXAMPLE $EXAMPLEDIR

cd ~/bin
saverepo "Added examples"
cd -
