#!/bin/sh
########################################################################
# 
# 	Scriptname	mvhobbies
# 
# 	Description:	renames and moves file to my hobbies dir
# 
########################################################################

HOBBIES=$@
HOBBIESDIR=$HOME/hobbies

rename_textfile $HOBBIES
test chmod 644 $HOBBIES
mv $HOBBIES $HOBBIESDIR
