#!/bin/sh
########################################################################
# 
# 	Scriptname	mvpersonal
# 
# 	Description:	renames and moves file to my personal dir
# 
########################################################################

PERSONAL=$@
PERSONALDIR=$HOME/writing/personal

rename_textfile $PERSONAL
test -d $PERSONAL && chmod 755 $PERSONAL || chmod 644 $PERSONAL
mv $PERSONAL $PERSONALDIR
