#!/bin/sh
########################################################################
# 
# 	Scriptname	mvteknotes
# 
# 	Description:	rename and mv to teknotes dir
# 
########################################################################

TEKNOTE=$@
TEKNOTESDIR=$HOME/teknotes

for note in $TEKNOTE
do
	rename_textfile $note
	test -d $note && chmod 755 $note || chmod 644 $note
	mv $note $TEKNOTESDIR
done

cd $TEKNOTESDIR
saverepo "Added ${TEKNOTE}"
cd -

