#!/bin/sh
########################################################################
# 
# 	Scriptname	mvwriting
# 
# 	Description:	renames and moves file to my writing dir
# 
########################################################################

WRITING=$@
WRITINGDIR=$HOME/writing

rename_textfile $WRITING
test -d $WRITING && chmod 755 $WRITING || chmod 644 $WRITING
mv $WRITING $WRITINGDIR

cd $WRITINGDIR
saverepo "Added ${WRITING}"
cd - 

