#!/bin/sh
########################################################################
# 
# 	Scriptname	remove_spaces 
# 
# 	Description:	remove spaces from filename replacing with _
# 
########################################################################

file=$@
newfile="$(echo ${file} | tr [\ ] [_])"

mv "${file}" ${newfile}

