#!/bin/sh

########################################################################
# 
# 	Scriptname	saverepo  
# 
# 	Description:	Add files to repo, commit and push
#	
#	Usage:		saverepo <description>
# 
########################################################################

DESC="$@"

git add .
git commit -m "${DESC}"
git push

