#!/bin/sh

########################################################################
# 
# 	Scriptname	timeloop
# 
# 	Description:
# 
# 	Run the 'loop' script and time execution
# 
########################################################################

loop $@
times
