#!/bin/sh -

xsetroot -name "resetting...."
sleep 1

printip() {
	wlan="$(ifconfig wlan0  2>/dev/null | grep inet | head -n 1 | cut -d ' ' -f 2)"
	ue="$(ifconfig ue0 2> /dev/null  | grep inet | head -n 1 | cut -d ' ' -f 2)"
	echo -n $wlan $ue 
}

printwho() {
	# echo -n "$(whoami)@$(hostname)"
	echo -n "$(hostname)"
}

printcpu(){
	echo -n "cpu:$(top -d 1 | grep -m 1 CPU | cut -d ',' -f 1 | cut -w  -f 2)"
}

printmem(){
	echo -n "$(top -d 1 | grep Mem |  sed 's/ [0-9]*M\ Buf,//' | cut -d ',' -f 4 |sed s/\ Free// | tr -d ' ')"
}

printload() {
	#echo -n "l:$(uptime | cut -d ':' -f 4  | sed -e 's/,.*//' -e 's/^ //')"
	echo "l:$(uptime | cut -d ':' -f 3  | cut -d ',' -f 1 | cut -w -f 2)"

}

printtime() {
	date "+%H:%M"
}

printdate() {
	echo -n "$(date | cut -d ' ' -f 1-4 | cut -d ':' -f 1-2)"
}

printbatt() {
	echo -n "b:$(/usr/sbin/acpiconf -i 0 | grep 'Remaining capacity' | cut -w -f 3 )"
}




while true 
do
	xsetroot -name "$(printtime) $(printdate)  $(printbatt),$(printload),$(printcpu),$(printmem)  $(printip)  $(printwho)"
	sleep 1
done

