#!/bin/sh

########################################################################
# 
# 	Scriptname	ccmtblock
# 
# 	Description:
# 
# 	Block comment /* ... */ all lines piped through stdin	
# 
########################################################################


echo "/*"
sed 's/^/ * /'
echo " */"

