#!/bin/sh

########################################################################
# 
# 	Scriptname	toascii
# 
# 	Description:
# 
# 	Convert stdin back to ascii (xxd format)	
# 
########################################################################

# ensure xxd is installed (part of vim)
[ ! -e /usr/local/bin/xxd ] && sudo pkg install -y -q vim  

xxd  -r
